version: "1"
rules:
  - base: master
    upstream: squidfunk:master
    mergeMethod: rebase
    mergeUnstable: false
    assignees:
      - simonusher
    conflictReviewers:
      - simonusher
    reviewers:
      - simonusher
label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict"